
  CREATE TABLE "SCOTT"."POS_TBL_CART" 
   (	"SERIALNO" NUMBER NOT NULL ENABLE, 
	"USERID" VARCHAR2(6 BYTE), 
	"FOODID" VARCHAR2(6 BYTE), 
	"TYPE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"COST" NUMBER NOT NULL ENABLE, 
	"ORDERDATE" DATE, 
	 CONSTRAINT "POS_TBL_CART_CHK1" CHECK (
quantity>0
) ENABLE, 
	 CONSTRAINT "POS_TBL_CART_CHK2" CHECK (
type in ('Veg','Non-Veg')
) ENABLE, 
	 CONSTRAINT "POS_TBL_CART_POS_TBL_USER_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "SCOTT"."POS_TBL_USER_CREDENTIALS" ("USERID") ENABLE, 
	 CONSTRAINT "POS_TBL_CART_POS_TBL_FOOD_FK1" FOREIGN KEY ("FOODID")
	  REFERENCES "SCOTT"."POS_TBL_FOOD" ("FOODID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
