
  CREATE TABLE "SCOTT"."POS_TBL_FOOD" 
   (	"FOODID" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"PRICE" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(10 BYTE), 
	"FOODSIZE" VARCHAR2(15 BYTE), 
	 CONSTRAINT "POS_TBL_FOOD_PK" PRIMARY KEY ("FOODID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "POS_TBL_FOOD_CHK1" CHECK (Type in ('Veg','Non-Veg')) ENABLE, 
	 CONSTRAINT "POS_TBL_FOOD_CHK2" CHECK (FoodSize in ('Small','Medium','Large')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
