
  CREATE TABLE "SCOTT"."POS_TBL_USER_PROFILE" 
   (	"LOCATION" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"USERID" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"STATE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PINCODE" VARCHAR2(10 BYTE), 
	"MOBILENO" VARCHAR2(10 BYTE), 
	"EMAILID" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"CITY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FIRSTNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"LASTNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DATEOFBIRTH" DATE NOT NULL ENABLE, 
	"GENDER" VARCHAR2(7 BYTE) NOT NULL ENABLE, 
	"STREET" VARCHAR2(30 BYTE), 
	 CONSTRAINT "POS_TBL_USER_PROFILE_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "POS_TBL_USER_PROFILE_POS__FK1" FOREIGN KEY ("USERID")
	  REFERENCES "SCOTT"."POS_TBL_USER_CREDENTIALS" ("USERID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE OR REPLACE TRIGGER "SCOTT"."POS_TBL_USER_PROFILE_TRG" 
 BEFORE INSERT ON POS_TBL_USER_PROFILE 
FOR EACH ROW 
BEGIN
  SELECT POS_SEQ_USERID.NEXTVAL INTO :NEW.USERID FROM DUAL;
END;


/
ALTER TRIGGER "SCOTT"."POS_TBL_USER_PROFILE_TRG" DISABLE;
 
