
  CREATE TABLE "SCOTT"."POS_TBL_CREDITCARD" 
   (	"CREDITCARDNUMBER" VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	"VALIDFROM" VARCHAR2(7 BYTE) NOT NULL ENABLE, 
	"VALIDTO" VARCHAR2(7 BYTE), 
	"BALANCE" NUMBER, 
	"USERID" VARCHAR2(6 BYTE), 
	 CONSTRAINT "POS_TBL_CREDITCARD_PK" PRIMARY KEY ("CREDITCARDNUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "POS_TBL_CREDITCARD_POS_TB_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "SCOTT"."POS_TBL_USER_PROFILE" ("USERID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
